# Generated by Django 5.0.6 on 2024-06-23 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 6, 23)),
            preserve_default=False,
        ),
    ]
